### ISSUE TITLE
Register / Login / Profile

### ISSUE THREAD

**Issue by pmattmann** [ecamp/ecamp3#1237]
# Register
- [x] #2834
- [x] #2835
- [x] Nutzungsbedingungen fehlen https://github.com/ecamp/ecamp-site/pull/12 #3157
- [ ] Opt-out für Sentry (und andere optionale Features)
- [ ] Cookie-Banner nötig gemäss neuem Datenschutzgesetz?
- [x] #2836
- [ ] Aktivierungs-Mail Inhalt überarbeiten
  - [x] Formulierung
  - [x] übersetzbar  #1731
  - [ ] Sonderzeichen-Behandlung (Script-Injection, ...)
- [x] Einladungs- und Aktivierungs-Links: Bisher hardcoded auf localhost:3000, muss von Environment Variablen abhängig gemacht werden #1731 #2546 
- [x] Absender-Adresse: Bisher hardcoded auf info@ecamp3.ch, muss von Environment Variablen abhängig gemacht werden #2546 
- [x] Mailadresse bereits vergeben, beliebige andere non-200 Responses: Frontend Fehlermeldung implementieren. Aktuell landet alles im Sentry.

# Login
Landing-Page gestallten (vorallem Inhalt) (noch nicht jetzt)
  (wo ist man gelandet; was ist eCamp?) #2539
- [x] User state beachten bei Login: Aktiviert? #3007
- [x] Login via Email ermöglichen #2545 

# PW Reset 
- [x] #2555

# Auth
- [x] Kombination PW & OAuth soll funktionieren
  - [x] PW vor OAuth funktioniert
  - [x] OAuth vor PW nicht; ~~PW soll im Profil setzbar sein~~

# Profil
- [x] User.name Datenbank-Feld löschen, Login läuft in Zukunft nur noch mit E-Mail #3004
- [x] Benutzername Input-Feld löschen
- [x] Benutzername wird nicht angezeigt
- [x] Passwort ändern
- [x] Mail-Adresse ändern #2800 
  - [ ] PW Eingabe erforderlich
  - [x] Mail-Verifizierung
  - [ ] Zustand-Anzeige (Verifizierung hängig)
  - [ ] Abbruch
- [x] Geburtstag entfernen
- [x] Lokalise.com "Werbung" verschieben

# Improvements
- [x]  Auch wenn OAuth Provider 1 bereits eingerichtet ist, soll Login via OAuth Provider 2 möglich sein (wenn die Mailadresse stimmt)
