### ISSUE TITLE
Team verwalten

### ISSUE THREAD

**Issue by pmattmann** [ecamp/ecamp3#1238]
# Einladen / Ausladen
- [x] Einladen, gewählte Rolle wird ignoriert
- [x] Funktion "Resend Invitation-Mail"
- [x] Schlüssel für einladen / aktivierne / pw-reset einheitlich; nicht erratbar
  (gleich wie Entity-Id, aber länger?)
- [x] InvitationKey sollte in der DB gehasht sein (#2382)
- [x] Letzter Manager kann Camp nicht verlassen/seine Rolle auf nicht auf Guest/Member stellen (review)
- [x] Wenn man das Camp verlässt, redirect auf meine Lager https://github.com/ecamp/ecamp3/issues/843
- [x] Einladung-Page mit Instruktion ergänzen (@manuelmeister )
- [x] Bei Einladung "Login" -> redirect zurück zu Einladung (OK) ; Daten werden aber nicht neu geladen -> Einladung wird nicht korrekt angezeigt #2993 
- [x] Resend Einladung -> ServerError
- [x] Falls aktive User nur ein "Verwalter" -> Rolle von eingelandenen "Verwalter" kann nicht geändert werden
- [x] #2898
- [x] Bei User-Übersicht: Einladen
  - [x] Mail-Validation (smiley: already implemented)
- [x] Offene Einladungen muss man deaktivieren können

# Rollen 
#1415

## Improvements
- [x] Einladung auf Mail mit Konto; Register-Option nicht so primary anbieten
- [ ] Team-Site:  Wenn jemand eingeladen wird: Progress-Indikator auf Invite-Button fehlt

# Ideen:
- [ ] Einladungs- / Register-Prozess verbessern (zwei Mails nötig? usw.)
  - [x] Beim Mail-Aktivierung pendente Einladungen zeigen?
