### ISSUE TITLE
Lager Administration

### ISSUE THREAD

**Issue by pmattmann** [ecamp/ecamp3#1239]
# Lager erstellen
- [x] Period Start nach End; Wird nicht validiert
- [x] Vergangene Lager "ausblenden"
- [x] Löschen-Funktion entfernen
- [x] Motto muss kein Pflichtfeld sein

# Lager bearbeiten
- [x] Gruppe-Name* / Lager-Name* / Motto
  - Editierbar / Non-Unique
- [x] Lager-Adresse erfassen (z.B. für Druck)
- [x] Lager-Name kann mit "<" &  ">" nicht umgehen
- [x] Lager-Name leer  ->  Fehlermeldung falsch

# Lager löschen
- [x] Danger-Zone

# Periode
- [x] Letzte Periode soll nicht löschbar sein
- [x] Periode verschieben -> Abhängige Daten mit ziehen (ScheduleEntries & Tagesverantwortliche) https://github.com/ecamp/ecamp3/issues/2468

# Kategorie
- [x] Content-Type-Liste (möglich in Edit-Dialog)
- [x] Layout-Struktur   /  zu diskutieren
- [x] Löschen falls noch Block vorhanden -> Meldung zeigen

**Comment by pmattmann** [comment]
Meeting:

- [x] Content-Type-Liste von Category ist aktuell eine "Favoriten-Liste" - Absicht?

**Comment by BacLuc** [comment]
everything is implemented
