### ISSUE TITLE
Story / RF

### ISSUE THREAD

**Issue by simfeld** [ecamp/ecamp3#1240]
Issues:

- [x] Roter Faden Übersicht auto refresh falls neuer RF content node vorhanden (existierende und neue content nodes, inkl. Title und Nummer) #1255 
- [x] In RF Übersicht Tage collapsible + vergangene Tage auto collapsed (analog zu Periode) #3038 
- [x] Roter Faden separat drucken #3036

Out of scope for MVP:
- Custom RF Elemente pro Tag / zwischen Blöcken
- In RF Übersicht neue RF Elemente hinzufügen
- Reihenfolge von mehreren RF content nodes im gleichen Block in RF Übersicht
