### ISSUE TITLE
Activity & Content Type

### ISSUE THREAD

**Issue by simfeld** [ecamp/ecamp3#1242]
Issues:

- [x] Activity Layout: #834
- [x] Column layout follow-up #1124
- [x] Bestehender activity neuer schedule entry hinzufügen/löschen/bearbeiten #1375 
- [x] Storyboard sort: #689 
- [x] Activity Titel in Block-Ansicht bearbeiten
- [x] Kategorie in Block-Ansicht ändern
- [x] Formatierung Rich Text Felder überall wo heute Textareas sind erlauben, konkret bei Roter Faden, Notizen, SiKo, Storyboard mittlere Spalte #2974 
- [x] ~~Notiz content type auf Freitext umbenennen~~
- [x] Strategies sollen sich von einer Vorlage kopieren / klonen können #1353
- [x] Review mobile view (especially for nested column layouts), je nach Outcome beim Print wird das Problem sowieso abgeschafft
- [x] Icons der content nodes: In MVP nicht konfigurierbar #2975 
- [x] Activities löschen? #2742
- [x] Storyboard Spalten Zeit und Verantwortlich auf (single-line) plain Text umschalten, nicht mehr Textarea #2974 

## Improvements
- [x] Usability: Kategorie und Titel in Blockansicht ändern, Funktion sichtbarer machen
- [x] After deletion of activity --> delete immediately from picasso (or mark visually as being deleted)

Out of scope for MVP:
- SiKo Übersicht editierbar (nur aggregiert)
- Lager-SiKo (bzw. Periode)
- Comments #828 
- Fortschritt Activity
- Spalten von Storyboard (Zeit, Programm, verantwortlich) umbenennbar machen
- Zeit-Spalte als Zeit-Datentyp anstatt Freitext (falls überhaupt)
- Weitere layout content types (weitergehend als Spaltenlayout)
- Checks auf content nodes (z.B. LS-Block muss mind. ein ausgefülltes SiKo enthalten)
- Kategorisierung content types #937
- Icons der content nodes konfigurierbar

**Comment by BacLuc** [comment]
Tasks are implemented.
Ideas came up again by us or were asked from users.
