### ISSUE TITLE
Picasso/Grobprogramm

### ISSUE THREAD

**Issue by manuelmeister** [ecamp/ecamp3#1243]
## Was fehlt?
- [x] Tageschef #1281 (in Print fehlt es noch: #1241)
- [x] Verantwortliche auf dem ScheduleEntry anzeigen (Avatar ohne Bild mit Buchstabe) #2965 
- [ ] _PostMVP?_: ScheduleEntryPopup Verantwortliche aufnehmen
- [x] ScheduleEntryPopup Tag anzeigen / bearbeiten (über verschiedene Perioden) #2350 #2351
- [x] ScheduleEntryPopup zusätzliche schedule entries hinzufügen #2350 #2351
- ~~Duplizeren: Initiiert mit Button aus ScheduleEntryPopup; Neues Formular öffnet, dort kann Tag+Zeit gewählt werden~~
- [x] ScheduleEntry löschen (nicht den letzten Entry) ~~bei letztem ScheduleEntry auch Activity löschen~~
- [x] Activity löschen #2742 
- [x] Validation auf ScheduleEntry auf Activity DeleteLastScheduleEntryNotAllowed (similar to Period & Camp)
       _(usu: Ich fände besser, wenn die Activity bewusst gelöscht werden muss und eine Validation bzw. Pre-Delete-Check drin zu haben, dass min. 1 ScheduleEntry drin bleibt) https://github.com/ecamp/ecamp3/commit/fef837a23e89996372471b9c27bbd923f2cce198
- [ ] ~~Mouseover: Alle Schedule Entries derselben Activity leuchten auf~~ Post MVP
- [ ] Dirty Handling auf Reload der Kalenderevents #2457
- [x] Frontendvalidation ScheduleEntry im Popup #2339
- [x] Bugs
  - [x] ScheduleEntryPopup Timepicker bei Endzeit anzeigen
  - [x] ScheduleEntryPopup Länge editierbar machen
  - [x] Rechtsklick auf ScheduleEntry öffnet ScheduleEntryPopup
  - [x] ScheduleEntryPopup required `(field) ist ein Pflichtfeld`
  - [x] Timepicker `Invalid date` Übersetzungsfehler
  - [x] Invalid Date Dauer Fehler NaN
  - [x] Drag & Drop von/zu derselben Stelle öffnet den Block (fälschlicherweise als Drag & Drop erkannt)
  - [x] Listenansicht entfernen #1260

## Improvements
- ScheduleEntryPopup UX weiterer ScheduleEntry hinzufügen (User sieht bei vielen Entries den Neuen evtl. nicht)
- Errormeldung im Picasso zB bei Verschieben ausserhalb der Periode
  - Block kann nicht über 23:59 Periodenende gezogen werden #2339
- reload bei idle (sollte wohl keine unresolved Requests vorhanden sein)
- #2424
- #2398
- Lesbare Links (Farbe)
- Hilfestellung im Lesemodus bei versuchtem Drag & Drop

## Diskussionspunkte
- Im Picasso kann nur dupliziert werden (deepcopy, mit Aktivität)
  - Mehr ScheduleEntries können innerhalb Activity View gemacht werden
- Inkonsistente Nummerierung nach Block-Verschieben
  - Workaround: Reload by Drag& Drop (ganzer Picasso oder Start-/Zieltag)

## Not MVP
- Mouseover: Alle Schedule Entries derselben Activity leuchten auf 
- Push Updates / Live-Reload
- Mehrere parallele Blöcke besser anzeigen
- Darstellungsoptionen
- Listenansicht / Tagesübersicht 
- Kopieren von Blöcker über Lagergrenzen
- Ctr/Alt + Drag& Drop für Duplizieren

**Comment by BacLuc** [comment]
I will close this for now
