### ISSUE TITLE
Meine Verantwortung / Welcome

### ISSUE THREAD

**Issue by simfeld** [ecamp/ecamp3#1244]
Use Cases:
- Ich als Mitleiter möchte herausfinden, an welchen Tagen ich oder jemand von meinen Mitleitenden viel zu tun habe mit Aktivitäten / als Tages-Chef
- Ich als Mitleiter möchte schnell zu meinen Blöcken navigieren und sehen welche Personen auch noch beteiligt sind
- ~~Ich möchte während der Planungsphase wissen, was noch aussteht bzw. was ich schon erledigt habe (Fortschritt)~~ Post MVP weil Fortschritt von Blöcken Post MVP ist

### MVP
- Dediziertes Dashboard / Landing Page im Lager
  - [x] Mit Links zu meinen Blöcken und mit wem zusammen ich diese schreibe
  - [x] #5064
  - [x] Tages-Verantwortlicher (Label) bei Datum-Zeile anzeigen, falls selber Tages-Verantwortlicher
- [x] ~~Picasso Verantwortliche User "Icon" zeigen  (PM)~~
- [x] Tageschef im Picasso ersichtlich und bearbeitbar #1281 
- [x] Loading verbessern #2763 

Verworfen: 
- Suche/Filter nach allen möglichen Arten von Inhalten und Möglichkeit, explizit nach Inhalten in meiner Verantwortung zu suchen

### Improvments
- [ ] Picasso einfärben können nach mir zugewiesenen Blöcken (Post MVP?)

### Post MVP
- Den User nach dem Login direkt in sein zuletzt angeschautes Lager navigieren
- Picasso nach Fortschritt färben

**Comment by BacLuc** [comment]
Remaining issues are extracted.
