### ISSUE TITLE
Material

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#1245]
### Open issues
- [x] On top level, group by Period or group by material list #1258
- [x] Trial with Vuetify data table? (for both matieral overview and acitivity content plugin) #1258 
- [x] ~~Add new item: Only sort after reload~~ Sort immediately, but show position with animation #1258
- [x] Liste löschen nur erlaubt wenn leer #2765 
- [ ] #5063
- [x] Excel download
  - Frontend solution: https://www.npmjs.com/package/vue-json-excel
  - Backend solution: https://github.com/PHPOffice/PhpSpreadsheet

### Bug
- [x] Eager adding items: Material list name not shown after response from server; glitch with styling #1258

### Improvement
- Sticky Header Table
- Spalten Besser verteilen (link zu Activity optimieren)

### To discuss
- Matrialliste Optional (post mvp)
- Who can create new material lists?
- Should we prevent deleting user connected material lists?

### Post MVP
- Create new material list directly from material selection dropdown 
- Eigene Artikel-Tabelle für Auto-Completion und/oder Kumulation
- Auto-completion für "Unit": Stück, liter, meter, etc.
- Edit after server error (im Moment geht nur retry/cance)

**Comment by BacLuc** [comment]
Mostly done
