### ISSUE TITLE
Migration zu API Platform

### ISSUE THREAD

**Issue by manuelmeister** [ecamp/ecamp3#1579]
### Tasks für die `API`
- [x] #1449 Reviewen & Mergen 
- [x] #1607
- [x] #1682 Embedded Entities Beispiel aufbauen @pmattmann 
- [x] Authentication (Username+Passwort im POC, es fehlt noch OAuth, Passwortreset, EMail-Verifikation #2003, Username ändern verhindern #1639) @simfeld #2030
- [x] CORS #2001
- [ ] Validierung (Beispiele im POC und in #1639)
  - [x] #2553
- [x] #1906 (Beispiel im POC) (@carlobeltrame)
- [x] Beispiel für nested POST (Camp mit Periode) #1639
- [x] #1679
- [x] Sauberes Datenbank Transaktionshandling #2391 #2536
- [x] Datafixtures (Beispiele im POC und in #1639)
  - [x] split fixtures into Prod & Dev (and maybe Test?) #2371 
- [x] #1716 (@BacLuc)
- [x] Sentry #1580 @manuelmeister 
- [x] Tests für API mitziehen (Beispiel im POC) #1639
  - [x] GraphQL Smoke Tests @BacLuc, in #1680
  - [ ] GraphQL Test für Operation -> warten auf API platform 2.7
- [x] Github Actions (Implementiert im POC, es fehlt noch Coveralls) #1681
- [x] Profile Endpoint ablösen #2005 
- [x] #1732
- [x] Sort php8 attributes https://github.com/ecamp/ecamp3/issues/1921
- [x] ~~Queue~~
- [x] #1943 (Ähnlich wie AbstractEntityService) 
- [x] Deployment #2002 #2353

### Anpassungen an `hal-json-vuex`
- [x] HTTP Headers 
- [x] ~~Authentifizierung JWT Tokens~~ nicht mehr nötig, weil JWT token via cookies gesendet werden kann

## Fragen
- Gleiche Datenbank? ~~(ja)~~ doch nicht mehr, Datenbankstruktur ist sowieso anders und entwickelt sich weiter
- Getrennte Setups (ja)
- Caddy? (ja)
- PHP8 (ja)
- Authentifizierung auch durch Cookies ~~(nein)~~ JWT Token in zwei Cookies ist anscheinend eine gute Lösung
- Entities vom legacy kopieren, Accessor auf public und Collections auf iterable setzen
