### ISSUE TITLE
Content Type Struktur

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#1732]
### General stuff
- [x] ContentNode als Basisklasse für Content Entities (SingleText, etc.) #1818 
- [x] Separater Endpunkt für ContentNode ja/nein? Für den Moment nur zum Lesen #2010
- [x] Erzeugen von neuen ContentNodes (direkt auf SingleText Endpunkt?) --> Im Moment nur via individueller Endpunkte #2010
- [x] OnCreate --> copy from prototype #2015 
- [x] Sortieren und Tree-Rearrengements von ContentNodes (List patch?) (https://symfony.com/bundles/StofDoctrineExtensionsBundle/current/index.html) #2292 
- [ ] ~~GraphQL~~ (wahrscheinlich erst mit API Platform 2.7 vernünftig unterstützt)
- [x] Namespacing (sowohl im Code als auch in URI) #1818
- [x] Swagger Docu (sanity check)
- [x] Generic Tests #2010
- [x] API Resource config: ACL + Normalization/Denormalization Groups #2010
- [x] ~~validate JSON config~~ json config wird ersetzt durch spezifische Config auf den einzelnen konkreten Entity Klassen
- [x] Entity filter #2102 
- [x] on create: Validate ContentType is compatible with Entity class #2171 

### Singletext
- [x] Doctrine/API Entity #1818
- [x] Tests #2010
- [x] API Resource config: ACL + Normalization/Denormalization Groups #2010
- [x] InputFilter HTMLPurify #2102 
- [x] on create --> copy from prototype (partially implemented; only text without ContentNode data) #2015 

### Storyboard
- [x]  Doctrine/API Entity #1818
- [x] Section sorting (list patch) #2292
- [x] API Resource config: ACL + Normalization/Denormalization Groups #2146
- [x] on create --> copy from prototype #2146

### MultiSelect
- [x]  Doctrine/API Entity #1818
- [x] API Resource config: ACL + Normalization/Denormalization Groups #2194
- [x] on create --> copy from prototype #2194

### Material
- [x]  Doctrine/API Entity #1818
- [x] API Resource config: ACL + Normalization/Denormalization Groups #2139
- [x] on create --> copy from prototype #2139

### ColumnLayout
- [x] Doctrine/API Entity #1818
- [x] API Resource config: ACL + Normalization/Denormalization Groups #2010
- [x] on create --> copy from prototype #2015 
- [x] validate JSON column config #2024

**Comment by usu** [comment]
## Meeting Notes
- ContentNode als Basisklasse für Content Entities (SingleText, etc.)
- TBC: Separater Endpunkt für ContentNode ja/nein?
- Erzeugen von neuen ContentNodes (direkt auf SingleText Endpunkt?)
- Sortieren und Tree-Rearrengements von ContentNodes (List patch?)
- GraphQL
- Namepspacing (sowohl im Code als auch in URI)
- Swagger Docu (sanity check)

**Comment by manuelmeister** [comment]
@usu können wir wohl schliessen, oder?

**Comment by usu** [comment]
> @usu können wir wohl schliessen, oder?

#2292 ist noch offen. Danach glaubs ja. Können aber gerne im nächsten Meeting kurz drüber schauen, ob für jemand noch was offen ist.
