### ISSUE TITLE
Features to fix with API Platform backend

### ISSUE THREAD

**Issue by BacLuc** [ecamp/ecamp3#2029]
- [x] /camp/:id does not return the role of the user's campCollaboration (siehe discussion in #2225) -> gelöst in #2121
- [x] #2060
- [x] Camp Member (Collaborators.vue)
(User kann nicht die namen von anderen Benutzern lesen) Funktioniert jetzt temporär, wird aber mit #2148 richtig gelöst
- [x] Invitation: der Invitations Endpoint wird mit /index.jsonhal nicht exposed, weshalb die verwendeten template links leider nicht mehr funktionieren. #2245
- [x] Activity/Category Layout: Mit der umstellung hat sich ein bisschen was geändert. Das Feld jsonConfig im Json ist weg für das ColumnLayout, + man muss sich überlegen, wie man die ContentNodes erstellt. Die ContentTypes geben jetzt(bald) die richtige URI dafür zurück, siehe: #2175 (implemented with #2280)

**Comment by carlobeltrame** [comment]
Alles erledigt
