### ISSUE TITLE
ScheduleEntry: validate timing is within the bounderies of the period

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#2339]
Add a validation to ensure periodOffset + length is before midnight of the last day of the period.

Now it's not even checked that the start time is within the period bounderies.

### ToDo
- [x] Backend validation that scheduleEntry cannot be longer than the period (fixed in #2484 

Fixed in #2967:
- [x] Frontend validation in Create/Edit Form for Date-Inputs
- [x] Restrict drag&drop such that a scheduleEntry cannot be shifted outside of the period boundary (both at start and end of the period) 
- [x] Improve error feedback in DialogActivityEdit --> show what has triggered an error
