### ISSUE TITLE
Validierung aller Entities (Vom alten Backend kopieren)

### ISSUE THREAD

**Issue by BacLuc** [ecamp/ecamp3#2553]
I merged the existing Validations/InputFilters with the ones from the old backend and added the once i thought would be helpful.
(Maybe some parts are not up to date, i finished it at commit 05edfbf).
If you have time, grab an entity, copy the validations to a separate issue, add the validations and the tests for it and we are happy to see your PR.

### ColumnLayout.php
- [x] JSON Schema von Columns
- [x] Columns müssen zusammen eine breite von 12 haben
- [x] Keine orphan children

### MaterialNode.php
**Done** (Zusätzliche Property von Contentnode kann nicht gepatched werden)

### MultiSelect.php
**Done** (Zusätzliche Property von Contentnode kann nicht gepatched werden)

### MultiSelectOption.php
- [x] translate key kann nicht gepatched werden
- [x] MaterialList kann nicht gepatched werden 
- [x] checked muss ein boolean sein (done with #2825 )
- [x] options must be null on create ( #2979)

### SingleText.php
- [x] CleanHtml

### Storyboard.php
**Done** (Zusätzliche Property von Contentnode kann nicht gepatched werden)
- [x] Letzte Zeile kann nicht gelöscht werden. #2995 

### StoryboardSection.php
- [x] StoryBoard must not be null (done with #2825 because the Section does not exist anymore)
- [x] column1-3: cleanhtml

### AbstractContentNodeOwner.php
**Done**

### Activity.php
Entity
- [x] At least one scheduleEntry must remain, or delete the activity when the last scheduleentry is deleted (else it might be difficult to delete the activity) #2903 
Properties
- [x] When creating an Activity, at least one ScheduleEntry must be present
- [x] Category must not be null
- [x] Camp must not be null
- [x] Title #2903 
  - [x] Length >0 and length <= 32
  - [x] no cleanhtml
  - [x] trim
- [x] Location #2903 
  - [x] ~~Length >0~~ (Default is empty string) and length <= 64
  - [x] no cleanhtml
  - [x] trim

### ActivityResponsible.php
**Done**

### BaseEntity.php
#2903
- [x] Id is not writable (one tests with a random entity
- [x] createTime is not writable
- [x] updateTime is not writable

### Camp.php
Entity
- [x] Camp has at least one manager #2363 
- [x] Camp has at least one period #1278 #2406  
- [ ] periods must not overlap (until #2454 is implemented)

Properties
- [ ] isPrototype not writable (maybe for people with extended privileges)
- [x] name
  - [x] Length >0 and length <= 32
  - [x] no cleanhtml
  - [x] trim
- [x] title
  - [x] Length >0 and length <= 32
  - [x] no cleanhtml
  - [x] trim
- [x] motto
  - [x] length <= 128
  - [x] no cleanhtml
  - [x] trim
- [x] addressName
  - [x] length <= 128
  - [x] no cleanhtml
  - [x] trim
- [x] addressStreet
  - [x] length <= 128
  - [x] no cleanhtml
  - [x] trim
- [x] addressZipcode
  - [x] length <= 128
  - [x] no cleanhtml
  - [x] trim
- [x] addressCity
  - [x] length <= 128
  - [x] no cleanhtml
  - [x] trim

### CampCollaboration.php
Entity
- [x] https://github.com/ecamp/ecamp3/pull/2363
- [x] https://github.com/ecamp/ecamp3/pull/2356
- [x] Either user or inviteEmail is set
Properties
- [x] camp has at least one manager #2363 
- [x] inviteEmail #2903 
  - [x] valid email
  - [x] length <= 128
- [x] status
  - [x] not null
  - [x] valid status
  - [x] valid transition
- [x] role
  - [x] not null
  - [x] valid role

### Category.php
Entity
- [x] Cannot be deleted as long as activities are linked to it (happened in #2536, 9dc67cf)
Properties
- [x] camp
  - [x] not null
  - [x] cannot be changed
- [x] short (#2919 )
  - [x] length > 0 && length <= 16
  - [x] no cleanhtml (#3014)
  - [x] trim
- [x] name (#2919 )
  - [x] length >0 && length <= 32
  - [x] no cleanhtml (#3014)
  - [x] trim
- [x] color
  - [x] valid color 
  - [x] not null
- [x] numbering style
  - [x] not null
  - [x] valid numbering style

### ContentNode.php
Properties
 - [x] Validate that the parent content node supports children (#2979)
 - [x] parent
   - [x] belongs to same owner
   - [x] no loop
   - [x] either is null or root is null, but not both and not both not null
 - [x] children
   - [x] Mostly done with the validation of the parent
   - [x] Validate that all children have a supported slot name (#3126) 
 - [x] position
   - [x] not null
   - [x] guarantee uniqueness of parent+slot+position (#3126 )
- [x] instanceName
  - [x] length >0 && length <= 32 (tests needed) (#3126 )
  - [x] trim (tests needed) (#3126 )
  - [x] CleanText (tests needed) (#3126 )
- [x] contenttype
  - [x] not null
  - [x] content type and content node are compatible

### ContentType.php
- [x] Create, update and delete is not possible

### Day.php
- [x] Create, update and delete is not possible

### DayResponsible.php
** Done **

### MaterialItem.php
- [x] materialList belongs to same camp
- [x] period
  - [x] belongs to same camp
  - [x] either is null (period and materialNode)
- [x] materialNode
  - [x] belongs to same camp
  - [x] either is null (period and materialNode)
- [x] article
  - [x] length >0 && length <= 32
  - [x] trim
- [x] quantity
  - [x] float
- [x] unit
  - [x] 0 <= length <= 32
  - [x] trim

### MaterialList.php
- [x] camp
  - [x] cannot be changed
- [ ] campCollaboration
  - [x] cannot be changed
  - [ ] Je nach dem either is null mit name, (TO BE DISCUSSED #2574)
- [x]  name
  - [x] 1 < length <= 32
  - [x] no cleanhtml (#3014)
  - [x] trim

### Period.php
- [x] camp
  - [x] cannot be changed
  - [ ] periods must not overlap (until #2454 is implemented)
- [x] Description (#2919 )
  - [x] length >0 && length <= 32 (In the old backend it was 128)
  - [x] no cleanhtml
  - [x] trim
- [x] start
  - [x] less than or equal to end
  - [x] less than or or equal to earliest schedule entry
  - [x] date (without time and without time zone), test is missing
- [x] end
  - [x] greater than or equal to start
  - [x] greater than or or equal to latest schedule entry
  - [x] date (without time and without time zone), test is missing

### Profile.php
- [x] email
  - [x] trim
  - [x] not blank, not null
  - [x] valid email
  - [x] unique
- [x] username
  - [x] trim
  - [x] not blank, not null
  - [x] unique
  - [x] pattern: /^[a-z0-9_.@-]+$/
- [x] firstname
  - [x] length <= 64
  - [x] no cleanhtml
  - [x] trim
- [x] surname
  - [x] length <= 64
  - [x] no cleanhtml
  - [x] trim
- [x] nickname
  - [x] length <= 32
  - [x] no cleanhtml
  - [x] trim
- [x] language
  - [x] valid language
  - [x] trim (Do we need a trim here?)
- [x] user
  - [x] not null (Assured because profile can only be created with nested post over user, and patch user is not allowed)

### ScheduleEntry.php
- [x] period
  - [x] cannot be null
  - [x] belongs to same camp as activity
- [x] activity
  - [x] not null
  - [x] belongs to same camp as period
  - [x] cannot be changed
- [ ] startOffset
  - [ ] must be inside period (wollen wir diese invariant?)
- [ ] endOffset
  - [ ] must be inside period (wollen wir diese invariant?)
- [ ] left
  - [ ] 0 <= left < 1 (was für ein minimalwert für die width ist sinnvoll?)
  - [ ] left + width = 1
- [ ] width
  - [ ] 0 < width <= 1
  - [ ] left + width = 1
- [x] start
  - [x] >= period.start
- [x] end
  - [x] <= period.end

### SortableEntityInterface.php
Validations können hoffentlich in SortableEntityTrait implementiert werden

### SortableEntityTrait.php

- [ ] position
  - [ ] -1 >= position

### User.php
- [x] activationKeyHash
  - [x] Is not writeable
- [x] password
  - [x] Is not writeable
- [x] passwordResetKeyHash
  - [x] Is not writeable
- [x] profile
  - [x] not null
  - [x] another profile cannot be referenced, a new profile must be created when creating a user
  - [x] you cannot link to another profile
  - [x] embedded patch is not allowed
  - [x] unique (assured by oneToOne)

**Comment by BacLuc** [comment]
I close this issue.
If we need anything more, it will pop up again.
