### ISSUE TITLE
Pre-Launch

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#2559]
### Api Platform Config
- [x] Disable features we don't use (input/output formats, disable graphql only on prod)

### Caddy Config
- [x]  Disable features we don't use.
  - e.g. http/2, http/3. We already use http/3 on deployment with firefox:
  

![Image](https://user-images.githubusercontent.com/1506818/193445772-2590c9ef-9323-471c-af0e-9b1c3494a044.png)

- [ ] Test features we use

### Deployment
- [x] Add deployment for production (and staging?) in environment separate from dev environment
- [x] Share necessary secrets/logins with team in a safe manner
- [x] Verify auto-scaling (load-test?)

### DB
- [x] Verify backup strategy
- [x] Concept to copy DB data from prod to stage regularly

### Caching/Performance
- [ ] PHP OPcache/JIT?
- [ ] DB query cache?
- [ ] [Reverse proxy cache](https://api-platform.com/docs/core/performance/) (Varnish; Caddy/Souis; Cloudflare)?
  - https://github.com/api-platform/api-platform/issues/2133
  - https://github.com/api-platform/core/issues/4512

### Admin
- [ ] [API platform admin interface](https://api-platform.com/docs/admin/)?

### Monitoring
- [x] Kubernetes performance monitoring
- [x] External alive monitoring (Pingdom?) https://status.ecamp3.ch

- [ ] Exclude Errors from Sentry which are no errors (https://stackoverflow.com/questions/64098722/sentry-on-symfony-how-to-exclude-notfoundhttpexception)
e.g. https://sentry.io/organizations/ecamp/issues/3116354532/?project=5912620&query=is%3Aunresolved

### Security
- [ ] Prevent brute-force attacks for anything exposed to non-authenticated users (create user, login, reset password, etc.)

### UX
- [x] Get detailed feedback by PfiLa & SoLa users about experience.

**Comment by carlobeltrame** [comment]
See also https://github.com/ecamp/ecamp3/projects/2

**Comment by darkweak** [comment]
Hey 👋, if you need help to setup Souin on your stack (configuration, pain points, questions), feel free to ping me.

**Comment by BacLuc** [comment]
Most things are implemented.
The rest will reappear
