### ISSUE TITLE
Minor UI bugs

### ISSUE THREAD

**Issue by carlobeltrame** [ecamp/ecamp3#3144]
### Mobile
- [ ] #3760
- [ ] #3761
- [x] ScheduleEntry Details: Can't exit editing an instance name without changing it (on desktop you can press ENTER) [[video]](https://user-images.githubusercontent.com/7566995/200416372-f7aabb21-9c28-4121-8282-44dfd20e9f34.mp4) #3147 

### Story overview
- [x] #3412 #3414

### Camp creation
- [x] The date pickers for the period date range should react to each other. If I select a start date in next July, the end date picker should automatically show July, and not allow to select dates before the start date. This is also true when creating and editing periods in the camp admin. #3172

### Camp admin
- [x] The period create button overlaps the line below it slightly [[screenshot]](https://user-images.githubusercontent.com/7566995/200602499-2fa6bb4f-169d-442f-bbbf-0d0c158dbc2b.png)

### Picasso
- [x] When using English as language, the validation for the end time on new schedule entries is wrong [[video]](https://user-images.githubusercontent.com/7566995/200603868-591270b5-31a9-4ae7-8cc4-ed750fa69f61.mp4) #3172
- ~~[ ] Use a tooltip instead of the title attribute for the lockicon doubleclick tip~~ We now have a single click
- [ ] #5059

### General
- [x] Currently, neither CategoryChip nor UserAvatar show the text in the correct contrast color [[screenshot]](https://user-images.githubusercontent.com/7566995/200597668-731efe3a-8f8c-4338-832f-b4eb6faf247f.png) #3154
- [x] #5062
- [x] In single line api-inputs, the green save icon overlaps the borders [[video]](https://user-images.githubusercontent.com/7566995/198699429-3e65f572-15f7-4add-a29c-6dbbf94c26d7.mp4) #3609?
- [ ] In single line e-inputs, the save and cancel buttons are misaligned vertically [[screenshot]](https://user-images.githubusercontent.com/7566995/200532125-3fec8e49-ded5-48ff-8d13-3314a5917c3c.png) maybe merge conflict with #3609
- [ ] #5060
- [x] Clicking inside the text field of a color or date picker should open the picker #3172
- [x] Color and date picker should not require clicking the okay button. Clicking a value in the picker should be enough to fill in the underlying input (and maybe even close the picker) #3172
- [x] #5061
- [x] Camp templates in the camp list should be explained or hidden to first-time users #3158
- [x] ScheduleEntry Details: The blue button in the material list content node is too small [[screenshot]](https://user-images.githubusercontent.com/7566995/200532522-dfbbb8cb-e5ea-4b10-b5bb-18c9eb6d210c.png)
- [ ] #3762

**Comment by BacLuc** [comment]
Closing this as we have all open issues in separate tickets
