### ISSUE TITLE
Picasso

### ISSUE THREAD

**Issue by manuelmeister** [ecamp/ecamp3#494]
**Desktop:**
- [x] ~~Mehrere Perioden gleichzeitig anzeigen~~
- [x] Für jede Periode einen Kalender einblenden (Prio 1)
- [x] ~~Von jedem Tag zu jedem Tag drag n drop~~
  - Jede Periode individuell rendern (Prio 1)
  - (Wenn möglich in einem Controll)
- [x] Kontextmenu
  - [x] OnCreate Dialog bleibt offen für allfällige Fehler oder Bestätigung, danach schliesst er automatisch
- [x] Neues Event zeichnen
- [x] Gestaltung (Farbe, Nummer, …)

Last option: selber implementieren

**Mobile:**
- [ ] Tage seitlich scrollen (swipen)
- [ ] Drag n Drop nicht zulassen
- [ ] Activity anzeigen, ohne Kontextmenus

**Überall:**
- [x] Mehr & weniger als 7 Täge ansehen können (Prio 1)

Evtl taucht #394 auf :)

Falls beim MVP mehrere Perioden zugelassen werden, dann nicht überlappend: #501

**Comment by carlobeltrame** [comment]
Noch offene Punkte werden in #666 abgehandelt
