### ISSUE TITLE
Checklist UI

### ISSUE THREAD

**Issue by usu** [ecamp/ecamp3#6018]
_Issue to collect open points regarding checklist UI._

# Checklist view

- [x] Text doesn't wrap (text overflow)

![image](https://github.com/user-attachments/assets/76885eb7-493f-4ee5-83f6-453c8bb23277)

- [x] Cannot delete items
- [x] When clicking on "Checklist Overview" item in sidebar while in checklist detail, it would be good to go back to the checklist overview. The same behavior as in material overview.
@BacLuc -> i think this is done

- [x] In activity layout mode, there should be no "Bearbeiten"
![image](https://github.com/user-attachments/assets/d2dbee36-8505-476e-b060-b008c87f2da9)

- [x] #10046

 

# Activity / Schedule Entry view
- [x] missing translation keys
![image](https://github.com/user-attachments/assets/a10e1490-8f5d-4460-9021-77d6b448c50c)
![image](https://github.com/user-attachments/assets/5131c9d9-c792-4c88-9168-2d6e3d6d2933)

- [x] edit dialog should have a close button
- [ ] I'd prefer a "edit" button (or better "select items") button instead of clicking on the already selected items

- [x] missing wrapping of long text breaks activity UI
![image](https://github.com/user-attachments/assets/7b7864ba-62c2-4663-b9c2-19826ccce42a)

**Comment by Jenish-1235** [comment]
Hello there, I would love to contribute to this issue during hacktoberfest 2024. Could you let me know, whether this issue is still there or not?

**Comment by BacLuc** [comment]
@usu 
Extracted the permission question of the checklist into separate issue.

I don't know what you mean with:
"I'd prefer a "edit" button (or better "select items") button instead of clicking on the already selected items"

If this is good enough, can you close the issue?

**Comment by carlobeltrame** [comment]
It's about how one can edit the selected checklist items in an activity.
Currently, you have to click on the area with the selected checklist items to change which items are selected:

<img width="463" height="331" alt="Image" src="https://github.com/user-attachments/assets/d141380f-3375-494e-b360-711d1c874d38" />

When no item is selected yet, it just shows an "Edit" label:
<img width="455" height="189" alt="Image" src="https://github.com/user-attachments/assets/2bd192cb-cfb9-4838-93dd-5864dde3eb90" />

Clicking this opens a hand-rolled modal dialog with accordions and switches:
<img width="582" height="441" alt="Image" src="https://github.com/user-attachments/assets/f54aebe3-3730-4502-88c9-7af31d086a6c" />

This differs e.g. from LA thematic area, where we have a multiselect dropdown:
<img width="461" height="218" alt="Image" src="https://github.com/user-attachments/assets/f118c6f2-6d13-4621-9926-19b9baef9193" />

"I'd prefer a "edit" button (or better "select items") button instead of clicking on the already selected items" refers to it being awkward to have no edit button and no caret to click when there are already some checklist items selected.

I'll create a new issue for this, since everything else has been completed.
