### ISSUE TITLE
Mobile version of camp program

### ISSUE THREAD

**Issue by manuelmeister** [ecamp/ecamp3#666]
- [x] Tage seitlich scrollen (swipen)
- [x] Drag n Drop nicht zulassen
- [x] Activity anzeigen, ohne Kontextmenus
