### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by manuelmeister** [ecamp/ecamp3#828]
Allow users to give feedback on activities.

Variants:
1. Simple activity content
2. Multiple comment types (Activity Comment, Day Comment, Material Comment, …)
3. Generic comment type with a reference to the respective entities.

**Comment by manuelmeister** [comment]
# Feedback/Comments

## MVP:
- [x] I'm able to leave comments on an activity (author, timestamp) (even as a guest) #10454
- [x] I'm able to delete my comments #10454
- [ ] Datamodel should be flexible (to be assigned to other entities/views/…)
  - [x] camp reference #10454
  - [ ] maybe soft references
- [x] Richtext (link, list, bold, italic, strikethrough, emoji) #10454
- [ ] Comments are not copied by prototype
- [ ] Comments should not be printed in the detail program
- [x] Cascade delete comments on activity delete? #7230
  - [x] Should they be deleted? If not, they should probably keep a human readable "reference" (eg. title) #10454
- [x] We decide that the max character length of a comment is `1024` #7230


## Advanced:
- [ ] I'm able to resolve/hide any comment?
- [ ] I'm able to mark as read/unread (only for me)
- [ ] I'm able to reply
- [ ] ~~I'm able to edit comments?~~
- [ ] I'm able to assign / mention?
- [ ] Overview page with activity comments
- [ ] Show me comments on objects I'm responsible
- [ ] I can see that new comments have been made
- [ ] Dashboard filter for comments
- [ ] Comment overview for all camps

## Ideas:
- Are there ready-made-solutions?
- ~~https://tiptap.dev/docs/comments/getting-started/overview~~ comment threads is a paid tiptap feature, plus needs their hosting backend for storage

**Comment by manuelmeister** [comment]
We've got feedback, that users want to have a comments overview similar to eCamp v2.

**Comment by BacLuc** [comment]
One idea for the UX: https://github.com/BacLuc/ecamp3/tree/feat/comments-google-docs
(inspired by https://github.com/PfadiMH/ecampv4/)

**Comment by carlobeltrame** [comment]
Priority todo list for the frontend implementation:
- [x] Make UI for creating, reading and deleting comments useable #10454
- [ ] Enable feature toggle #10454
- [x] On Dashboard, indicate activities with comments and allow to view them #10454
- [x] Add a place to display orphan comments or comments on the camp itself, without activity reference #10454
- [ ] Enable comment threads (part of [example implementation](https://github.com/ecamp/ecamp3/compare/devel...BacLuc:ecamp3:feat/comments-google-docs))
- [ ] Allow to resolve and unresolve comments (part of [example implementation](https://github.com/ecamp/ecamp3/compare/devel...BacLuc:ecamp3:feat/comments-google-docs))
- [ ] Allow to anchor comments to different entities or more precise anchors in content nodes (e.g. rich text [range](https://tiptap.dev/docs/comments/getting-started/overview), schedule entry on picasso) ~~and re-anchor them if orphaned (also present in the [example implementation](https://github.com/ecamp/ecamp3/compare/devel...BacLuc:ecamp3:feat/comments-google-docs) but prefer to use the tiptap extension if possible, and make it more flexible than just rich text fields)~~
- [ ] Personal notification bubble with read markers
- [ ] Allow to mention specific people and notify them this way
- [ ] Allow to anchor comments to multiple entities at the same time and reference them in the comment text
- [ ] Notification system with push notifications
- [ ] Dashboard filter by activities which have comments
- [ ] Comments overview across all (or all future) camps (if still really necessary once we have the notification system)

**Comment by manuelmeister** [comment]
## Offline Discussion

Vision discussion by @carlobeltrame and @manuelmeister for comments UX/UI

### Vision
We primarily focused on desktop. We identified the following important functionalities:
- **A**: Camp Manager & J+S Coach can create comments anchored to an activity, part of an activity, the whole camp or other entities
- **B**: While creating a comment, the user needs to see the context of the commented content and previous comments
- **C**: Everyone should be able to easily view comments on the current visible entity, especially the ones they are responsible for
- **D**: Any comments should only be shown where we have enough context (such as activity comments in the activity detail view)
- **E**: Everyone should be able to resolve comments
- **F**: Resolved comments should be hidden by default, but discoverable
- **G**: When a commented entity is deleted, the comments become detached but should still be visible and not automatically be resolved
- **H**: The user is only able to indefinitely delete their comments
- **I**: Everyone should be able to reply to a "non-reply"-comment (thus comment nesting depth is 1)
- **J**: To work through feedback/tasks, the user should see the whole list of comments of their responsibilities.
- **K**: To have an overview of the current state of the planning, camp managers and J+S coaches need to be able to list all comments and to be able to filter by various criteria (resolved, period, detatched)
- **L**: The comment tries to stay attached as close to the initial entity/anchor as possible (uses a fallback system camp<activity<contentnode<path)
- **M**: Activity-orphaned comments need to be separately visible along side the "whole camp level" comments
- **N**: Users want to see an indication for new comments

### Todos / Decisions
- [x] Put category `shortName` into `orphanDescription` to help remember deleted activity contents
- [ ] orphanDescription should happen on comment creation instead of activity deletion
- [ ] Replace `orphanDescription` with columns for each entity referenced in the comment called `entity_CONTEXT` that saves a human readable snapshot summary of the referenced entity at the time of comment creation. This way on foreign deletion, we can give the user some context. If a comment is anchored to a text range, we also store the human readable snapshot of that text range in the column `anchor_context`.
- [x] On `ActivityRow` comment button click, it should navigate to the activity, open the comment panel and focus it
- [x] CommentPanel on Desktop: in non-activity-detail views we hide activity/contentnode/... comments, and instead add a small notice of the additional comments in each activity
- [x] CommentPanel on Mobile: show all comments
- [x] Mobile comments panel should be fullscreen
- [ ] Mobile comments panel should also have Filters/Sorting/... (for the moment only filterable by author, and resolved status)
- [x] Mobile comments panel on camp level should include all comments of any entity/deleted activities of this camp
- [x] When opening the CommentPanel on the Dashboard on Mobile via a button on an ActivityRow, display only the comments related to that activity (filter by that activity)
- [x] Comment background color use avatar color with hsl to help 
   ```js
  function lightenColor(color, lightness = 95) {
    const input = new Color(color)
    input.hsl.l=lightness
    return input.toString({ format: 'hex' })
  }
  ```

### Open Questions
- Mobile: Should I be able to resize comment panel, or fullscreen by default? -> fullscreen, we don't have space either way on mobile to display the whole necessary context
- Period comments?

**Comment by manuelmeister** [comment]
## Core Meeting Decision

- Comments on activity can't have period reference. If we want a period reference then we can still do that.
- We want to merge and ship this pretty soon, there are some minor changes needed.
- Hide activity comments in whole camp comment overview
- We discussed what happens to detached comments (especially for all snapshot context), but did not yet find a common ground and are going forward with this as it is now (with shortName of category).
- We agreed that comments on text ranges should persist the text range content at comment creation
